# Generated by Django 6.0 on 2025-12-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('url', models.URLField(unique=True)),
                ('sku', models.CharField(max_length=64, unique=True)),
                ('mpn', models.CharField(blank=True, max_length=64)),
                ('manufacturer', models.CharField(blank=True, max_length=128)),
                ('color', models.CharField(blank=True, max_length=128)),
                ('memory', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='UAH', max_length=8)),
                ('images', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('screen_size', models.CharField(blank=True, max_length=64)),
                ('resolution', models.CharField(blank=True, max_length=64)),
                ('characteristics', models.JSONField(blank=True, default=dict)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('raw_jsonld', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
